In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import trim_mean
import wquantiles
from statsmodels import robust

In [4]:
b1 = pd.read_csv("C:\\Users\\himan\\OneDrive\\Desktop\\csv\\Machine Learning\\BostonHousing.csv")
b1.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [5]:
b1.tail(20)

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
486  5.69175  0.0  18.10   0.0  0.583  6.114  79.8  3.5459   24  666     20.2   
487  4.83567  0.0  18.10   0.0  0.583  5.905  53.2  3.1523   24  666     20.2   
488  0.15086  0.0  27.74   0.0  0.609  5.454  92.7  1.8209    4  711     20.1   
489  0.18337  0.0  27.74   0.0  0.609  5.414  98.3  1.7554    4  711     20.1   
490  0.20746  0.0  27.74   0.0  0.609  5.093  98.0  1.8226    4  711     20.1   
491  0.10574  0.0  27.74   0.0  0.609  5.983  98.8  1.8681    4  711     20.1   
492  0.11132  0.0  27.74   0.0  0.609  5.983  83.5  2.1099    4  711     20.1   
493  0.17331  0.0   9.69   0.0  0.585  5.707  54.0  2.3817    6  391     19.2   
494  0.27957  0.0   9.69   0.0  0.585  5.926  42.6  2.3817    6  391     19.2   
495  0.17899  0.0   9.69   0.0  0.585  5.670  28.8  2.7986    6  391     19.2   
496  0.28960  0.0   9.69   0.0  0.585  5.390  72.9  2.7986    6  391     19.2   
497  0.26838  0.0   9.69   0.0  0.585  5.794  70.6  2.8927    6  391     19.2   
498  0.23912  0.0   9.69   0.0  0.585  6.019  65.3  2.4091    6  391     19.2   
499  0.17783  0.0   9.69   0.0  0.585  5.569  73.5  2.3999    6  391     19.2   
500  0.22438  0.0   9.69   0.0  0.585  6.027  79.7  2.4982    6  391     19.2   
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273     21.0   

          B  LSTAT  MEDV  
486  392.68  14.98  19.1  
487  388.22  11.45  20.6  
488  395.09  18.06  15.2  
489  344.05  23.97   7.0  
490  318.43  29.68   8.1  
491  390.11  18.07  13.6  
492  396.90  13.35  20.1  
493  396.90  12.01  21.8  
494  396.90  13.59  24.5  
495  393.29  17.60  23.1  
496  396.90  21.14  19.7  
497  396.90  14.10  18.3  
498  396.90  12.92  21.2  
499  395.77  15.10  17.5  
500  396.90  14.33  16.8  
501  391.99    NaN  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [6]:
# Checking the shape of data.
b1.shape

(506, 14)

In [7]:
b1.size

7084

In [8]:
b1.to_excel

<bound method NDFrame.to_excel of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396

In [9]:
type(b1)

pandas.core.frame.DataFrame

In [14]:
# checking type of data
b1["CHAS"].dtype

dtype('float64')

In [17]:
b1.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX          int64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [19]:
b1.CHAS.dtype

dtype('float64')

In [21]:
# Slicing
b1.iloc[:,1:3]

ZN  INDUS
0    18.0   2.31
1     0.0   7.07
2     0.0   7.07
3     0.0   2.18
4     0.0   2.18
..    ...    ...
501   0.0  11.93
502   0.0  11.93
503   0.0  11.93
504   0.0  11.93
505   0.0  11.93

[506 rows x 2 columns]

In [22]:
b1.loc[1:4,]

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
1  0.02731  0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729  0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237  0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905  0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [23]:
b1.loc[:,"ZN":"INDUS"]  # label based slicing.

ZN  INDUS
0    18.0   2.31
1     0.0   7.07
2     0.0   7.07
3     0.0   2.18
4     0.0   2.18
..    ...    ...
501   0.0  11.93
502   0.0  11.93
503   0.0  11.93
504   0.0  11.93
505   0.0  11.93

[506 rows x 2 columns]

In [27]:
b1["CRIM"].unique()  #Extracting the unique variable from crim column.

array([6.32000e-03, 2.73100e-02, 2.72900e-02, 3.23700e-02, 6.90500e-02,
       2.98500e-02, 8.82900e-02, 1.44550e-01, 2.11240e-01, 1.70040e-01,
       2.24890e-01, 1.17470e-01, 9.37800e-02, 6.29760e-01, 6.37960e-01,
       6.27390e-01, 1.05393e+00, 7.84200e-01, 8.02710e-01, 7.25800e-01,
       1.25179e+00, 8.52040e-01, 1.23247e+00, 9.88430e-01, 7.50260e-01,
       8.40540e-01, 6.71910e-01, 9.55770e-01, 7.72990e-01, 1.00245e+00,
       1.13081e+00, 1.35472e+00, 1.38799e+00, 1.15172e+00, 1.61282e+00,
       6.41700e-02, 9.74400e-02, 8.01400e-02, 1.75050e-01, 2.76300e-02,
       3.35900e-02, 1.27440e-01, 1.41500e-01, 1.59360e-01, 1.22690e-01,
       1.71420e-01, 1.88360e-01, 2.29270e-01, 2.53870e-01, 2.19770e-01,
       8.87300e-02, 4.33700e-02, 5.36000e-02,         nan, 1.36000e-02,
       1.31100e-02, 2.05500e-02, 1.43200e-02, 1.54450e-01, 1.03280e-01,
       1.49320e-01, 1.71710e-01, 1.10270e-01, 1.26500e-01, 1.95100e-02,
       3.58400e-02, 4.37900e-02, 5.78900e-02, 1.35540e-01, 1.281

In [28]:
b1["PTRATIO"].unique()

array([15.3, 17.8, 18.7, 15.2, 21. , 19.2, 18.3, 17.9, 16.8, 21.1, 17.3,
       15.1, 19.7, 18.6, 16.1, 18.9, 19. , 18.5, 18.2, 18. , 20.9, 19.1,
       21.2, 14.7, 16.6, 15.6, 14.4, 12.6, 17. , 16.4, 17.4, 15.9, 13. ,
       17.6, 14.9, 13.6, 16. , 14.8, 18.4, 19.6, 16.9, 20.2, 15.5, 18.8,
       22. , 20.1])

In [29]:
b1["LSTAT"].unique()

array([ 4.98,  9.14,  4.03,  2.94,   nan,  5.21, 12.43, 19.15, 29.93,
       17.1 , 20.45, 13.27, 15.71,  8.26, 10.26,  8.47,  6.58, 14.67,
       11.69, 11.28, 21.02, 13.83, 18.72, 19.88, 16.3 , 16.51, 14.81,
       17.28, 12.8 , 11.98, 22.6 , 13.04, 27.71, 18.35, 20.34, 11.41,
        8.77, 10.13,  4.32,  1.98,  4.84,  5.81,  7.44,  9.55, 10.21,
       14.15, 18.8 , 30.81, 16.2 , 13.45,  9.43,  5.28,  8.43, 14.8 ,
        4.81,  5.77,  3.95,  6.86,  9.22, 13.15, 14.44,  6.73,  9.5 ,
        8.05,  4.67, 10.24,  8.1 , 13.09,  8.79,  6.72,  9.88,  5.52,
        6.78,  8.94, 11.97, 10.27, 12.34,  5.29,  7.22,  7.51,  9.62,
        6.53, 12.86,  5.5 ,  5.7 ,  8.81,  8.2 ,  8.16,  6.21, 10.59,
        6.65, 11.34,  4.21,  3.57,  6.19,  9.42,  7.67, 10.63, 13.44,
       12.33, 16.47, 18.66, 14.09, 12.27, 15.55, 13.  , 10.16, 16.21,
       17.09, 10.45, 15.76, 10.3 , 15.37, 13.61, 14.37, 14.27, 17.93,
       25.41, 17.58, 27.26, 17.19, 15.39, 18.34, 12.6 , 12.26, 11.12,
       15.03, 17.31,

In [30]:
b1["INDUS"].unique()

array([ 2.31,  7.07,  2.18,  7.87,  8.14,  5.96,   nan,  2.95,  6.91,
        5.64,  4.  ,  1.22,  0.74,  1.32,  5.13,  1.38,  3.37,  6.07,
       10.81, 12.83,  4.86,  4.49,  3.41, 15.04,  2.89,  8.56, 10.01,
       25.65, 21.89, 19.58,  4.05,  2.46,  3.44,  2.93,  0.46,  1.52,
        1.47,  2.03,  2.68, 10.59, 13.89,  6.2 ,  4.93,  5.86,  3.64,
        3.75,  3.97,  6.96,  6.41,  3.33,  1.21,  2.97,  2.25,  1.76,
        5.32,  4.95, 13.92,  2.24,  6.09,  9.9 ,  7.38,  3.24,  6.06,
        5.19,  1.89,  3.78,  4.39,  4.15,  2.01,  1.25,  1.69,  2.02,
        1.91, 18.1 , 27.74,  9.69, 11.93])

In [31]:
b1["RAD"].unique()

array([ 1,  2,  3,  5,  4,  8,  6,  7, 24], dtype=int64)

In [38]:
b1.CRIM.values

array([6.32000e-03, 2.73100e-02, 2.72900e-02, 3.23700e-02, 6.90500e-02,
       2.98500e-02, 8.82900e-02, 1.44550e-01, 2.11240e-01, 1.70040e-01,
       2.24890e-01, 1.17470e-01, 9.37800e-02, 6.29760e-01, 6.37960e-01,
       6.27390e-01, 1.05393e+00, 7.84200e-01, 8.02710e-01, 7.25800e-01,
       1.25179e+00, 8.52040e-01, 1.23247e+00, 9.88430e-01, 7.50260e-01,
       8.40540e-01, 6.71910e-01, 9.55770e-01, 7.72990e-01, 1.00245e+00,
       1.13081e+00, 1.35472e+00, 1.38799e+00, 1.15172e+00, 1.61282e+00,
       6.41700e-02, 9.74400e-02, 8.01400e-02, 1.75050e-01, 2.76300e-02,
       3.35900e-02, 1.27440e-01, 1.41500e-01, 1.59360e-01, 1.22690e-01,
       1.71420e-01, 1.88360e-01, 2.29270e-01, 2.53870e-01, 2.19770e-01,
       8.87300e-02, 4.33700e-02, 5.36000e-02,         nan, 1.36000e-02,
       1.31100e-02, 2.05500e-02, 1.43200e-02, 1.54450e-01, 1.03280e-01,
       1.49320e-01, 1.71710e-01, 1.10270e-01, 1.26500e-01, 1.95100e-02,
       3.58400e-02, 4.37900e-02, 5.78900e-02, 1.35540e-01, 1.281

In [39]:
b1.mean()

CRIM         3.611874
ZN          11.211934
INDUS       11.083992
CHAS         0.069959
NOX          0.554695
RM           6.284634
AGE         68.518519
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.715432
MEDV        22.532806
dtype: float64

In [41]:
b1.CRIM.mean() # Using mean() in the data frame willl return mean of the dataframe across all the column.

3.6118739711934156

In [43]:
b1.median()

CRIM         0.253715
ZN           0.000000
INDUS        9.690000
CHAS         0.000000
NOX          0.538000
RM           6.208500
AGE         76.800000
DIS          3.207450
RAD          5.000000
TAX        330.000000
PTRATIO     19.050000
B          391.440000
LSTAT       11.430000
MEDV        21.200000
dtype: float64

In [ ]:
# USing mode() on the data frame will return mode values of the Dataframe across all the columns,rows with axis=0 and axis=1
# ,respectively

In [51]:
b1.mode(axis=0) # vertical

CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
0   0.01501  0.0   18.1   0.0  0.538  5.713  100.0  3.4952  24.0  666.0   
1  14.33370  NaN    NaN   NaN    NaN  6.127    NaN     NaN   NaN    NaN   
2       NaN  NaN    NaN   NaN    NaN  6.167    NaN     NaN   NaN    NaN   
3       NaN  NaN    NaN   NaN    NaN  6.229    NaN     NaN   NaN    NaN   
4       NaN  NaN    NaN   NaN    NaN  6.405    NaN     NaN   NaN    NaN   
5       NaN  NaN    NaN   NaN    NaN  6.417    NaN     NaN   NaN    NaN   

   PTRATIO      B  LSTAT  MEDV  
0     20.2  396.9   6.36  50.0  
1      NaN    NaN   7.79   NaN  
2      NaN    NaN   8.05   NaN  
3      NaN    NaN  14.10   NaN  
4      NaN    NaN  18.13   NaN  
5      NaN    NaN    NaN   NaN

In [52]:
b1.mode(axis=1)  # HOrizontal

0        1      2    3     4     5     6      7     8     9     10  \
0    0.0  0.00632  0.538  1.0  2.31  4.09  4.98  6.575  15.3  18.0  24.0   
1    0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
2    0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
3    0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
4    0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
..   ...      ...    ...  ...   ...   ...   ...    ...   ...   ...   ...   
501  0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
502  0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
503  0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
504  0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   
505  0.0      NaN    NaN  NaN   NaN   NaN   NaN    NaN   NaN   NaN   NaN   

       11     12     13  
0    65.2  296.0  396.9  
1     NaN    NaN    NaN  
2     NaN    NaN    NaN  
3     NaN    NaN    NaN  
4     NaN    NaN    NaN  
..    ...    ...    ...  
501   NaN    NaN    NaN  
502   NaN    NaN    NaN  
503   NaN    NaN    NaN  
504   NaN    NaN    NaN  
505   NaN    NaN    NaN  

[506 rows x 14 columns]

In [53]:
x = pd.DataFrame({"a":{1:"Welcome",2:"to"},"b":{1:"hello",2:"hii"}})
x

a      b
1  Welcome  hello
2       to    hii

In [67]:
y = pd.DataFrame({"a":[1,2,3,4],"b":[5,6,7,8]})
y

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [68]:
y.mode(axis=0)

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [69]:
y.mode(axis=1) 

0  1
0  1  5
1  2  6
2  3  7
3  4  8